const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const LS = { key:'rhstudio.apiKey', app:'rhstudio.appId', nodes:'rhstudio.nodes', inst:'rhstudio.instanceType', queue:'rhstudio.personalQueue' };
const state = { rows:[], task:null, poll:null, running:false };
const uid = () => Math.random().toString(36).slice(2,9);
const makeRow = kind => ({ id:uid(), kind:kind||'text', nodeId:'', fieldName:kind==='file'?'image':'value', fieldValue:'', file:null, fileName:'', uploadedValue:'' });
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg,type=''){ const e=$('#toast'); e.textContent=msg; e.className='toast show '+type; clearTimeout(e._t); e._t=setTimeout(()=>e.className='toast',2600); }
function apiKey(){ return localStorage.getItem(LS.key)||''; }
function maskKey(k){ if(!k)return ''; if(k.length<10)return '••••••••'; return k.slice(0,4)+'••••••••'+k.slice(-4); }
function updateKeyUI(){ const k=apiKey(), ok=!!k; $('#sideDot').className='dot '+(ok?'ok':''); $('#sideStatus').textContent=ok?'API Key 已配置':'API Key 未配置'; $('#keyWarning').classList.toggle('hidden',ok); $('#settingsDot').className='dot '+(ok?'ok':''); $('#keyStatusText').textContent=ok?'已保存 API Key':'尚未保存 API Key'; $('#keyMask').textContent=ok?maskKey(k):''; $('#settingsBadge').textContent=ok?'CONFIGURED':'NOT CONFIGURED'; $('#settingsBadge').style.color=ok?'var(--good)':'var(--accent)'; }
function route(name){ location.hash=name==='settings'?'#/settings':'#/workspace'; }
function renderRoute(){ const isSettings=location.hash.includes('settings'); $('#workspacePage').classList.toggle('hidden',isSettings); $('#settingsPage').classList.toggle('hidden',!isSettings); $('#crumbTitle').textContent=isSettings?'设置':'工作台'; $$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.route===(isSettings?'settings':'workspace'))); if(isSettings) $('#apiKeyInput').value=''; updateKeyUI(); }
$$('.navbtn').forEach(b=>b.onclick=()=>route(b.dataset.route)); window.addEventListener('hashchange',renderRoute);
function persist(){ localStorage.setItem(LS.app,$('#appId').value); localStorage.setItem(LS.inst,$('#instanceType').value); localStorage.setItem(LS.queue,$('#personalQueue').value); const safe=state.rows.map(r=>({id:r.id,kind:r.kind,nodeId:r.nodeId,fieldName:r.fieldName,fieldValue:r.kind==='file'?'':r.fieldValue,fileName:''})); localStorage.setItem(LS.nodes,JSON.stringify(safe)); }
function load(){ $('#appId').value=localStorage.getItem(LS.app)||''; $('#instanceType').value=localStorage.getItem(LS.inst)||'default'; $('#personalQueue').value=localStorage.getItem(LS.queue)||'false'; try{ const a=JSON.parse(localStorage.getItem(LS.nodes)||'[]'); state.rows=Array.isArray(a)&&a.length?a:[makeRow('text')]; }catch{state.rows=[makeRow('text')]} renderNodes(); }
['appId','instanceType','personalQueue'].forEach(id=>$('#'+id).addEventListener('input',persist));
function renderNodes(){ const box=$('#nodes'); box.innerHTML=''; state.rows.forEach(r=>{ const el=document.createElement('div'); el.className='node'; el.innerHTML=`<div class="nodegrid"><input class="input" data-k="nodeId" placeholder="Node ID" value="${esc(r.nodeId)}"><input class="input" data-k="fieldName" placeholder="fieldName" value="${esc(r.fieldName)}"><select data-k="kind"><option value="text" ${r.kind==='text'?'selected':''}>Text</option><option value="number" ${r.kind==='number'?'selected':''}>Number</option><option value="boolean" ${r.kind==='boolean'?'selected':''}>Boolean</option><option value="file" ${r.kind==='file'?'selected':''}>File</option></select><button class="remove">×</button></div><div class="nodeval"></div>`;
      el.querySelectorAll('[data-k]').forEach(inp=>inp.oninput=e=>{ const k=e.target.dataset.k; r[k]=e.target.value; if(k==='kind'){ if(r.kind==='file'&&!r.fieldName)r.fieldName='image'; renderNodes(); } else { persist(); countNodes(); } });
      el.querySelector('.remove').onclick=()=>{ state.rows=state.rows.filter(x=>x.id!==r.id); if(!state.rows.length)state.rows=[makeRow('text')]; renderNodes(); persist(); };
      const v=el.querySelector('.nodeval');
      if(r.kind==='file'){
        v.innerHTML=`<div class="filebox"><strong>${r.fileName?esc(r.fileName):'选择本地文件'}</strong><small>${r.fileName?'运行时会先上传到 RunningHub':'图片 / 视频 / 音频 / 其他文件'}</small></div>${r.fileName?`<div class="filename">${esc(r.fileName)}</div>`:''}<input type="file" hidden>`;
        const fi=v.querySelector('input'); v.querySelector('.filebox').onclick=()=>fi.click(); fi.onchange=()=>{ const f=fi.files[0]; if(!f)return; r.file=f; r.fileName=f.name; r.uploadedValue=''; renderNodes(); };
      } else if(r.kind==='boolean'){
        v.innerHTML=`<select><option value="false">false</option><option value="true">true</option></select>`; const inp=v.querySelector('select'); inp.value=r.fieldValue||'false'; inp.oninput=e=>{r.fieldValue=e.target.value;persist()};
      } else if(r.kind==='number'){
        v.innerHTML=`<input class="input" type="number" step="any" placeholder="数值" value="${esc(r.fieldValue)}">`; const inp=v.querySelector('input'); inp.oninput=e=>{r.fieldValue=e.target.value;persist()};
      } else {
        v.innerHTML=`<textarea placeholder="参数值 / Prompt">${esc(r.fieldValue)}</textarea>`; const inp=v.querySelector('textarea'); inp.oninput=e=>{r.fieldValue=e.target.value;persist()};
      }
      box.appendChild(el);
    }); countNodes(); }
function countNodes(){ const n=state.rows.filter(r=>r.nodeId.trim()&&r.fieldName.trim()).length; $('#nodeCount').textContent=n+' 个有效节点'; }
$('#addParam').onclick=()=>{state.rows.push(makeRow('text'));renderNodes();persist()}; $('#addFile').onclick=()=>{state.rows.push(makeRow('file'));renderNodes();persist()};
async function uploadRow(r,key){ if(!r.file) throw new Error(`节点 ${r.nodeId||'?'} 尚未选择文件`); const fd=new FormData(); fd.append('file',r.file,r.file.name); const res=await fetch('/api/rh/upload',{method:'POST',headers:{'x-rh-key':key},body:fd}); const data=await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error||`文件上传失败 (${res.status})`); const value=data?.data?.fileName||data?.data?.download_url||data?.fileName||data?.download_url; if(!value) throw new Error('RunningHub 上传接口未返回可用文件值'); r.uploadedValue=value; return value; }
async function runTask(){ if(state.running)return; const key=apiKey(); if(!key){toast('请先在设置页保存 API Key','bad');route('settings');return} const appId=$('#appId').value.trim(); if(!appId)return toast('请填写 AI App ID','bad'); const ready=state.rows.filter(r=>r.nodeId.trim()&&r.fieldName.trim()); if(!ready.length)return toast('至少需要一个有效节点','bad'); state.running=true; $('#runBtn').disabled=true; $('#runBtn').textContent='提交中…'; try{
    const nodeInfoList=[]; for(const r of ready){ let val=r.fieldValue; if(r.kind==='file'){ $('#runBtn').textContent='上传文件…'; val=await uploadRow(r,key); } nodeInfoList.push({nodeId:r.nodeId.trim(),fieldName:r.fieldName.trim(),fieldValue:String(val??''),description:null}); }
    $('#runBtn').textContent='提交任务…'; const res=await fetch('/api/rh/run',{method:'POST',headers:{'Content-Type':'application/json','x-rh-key':key},body:JSON.stringify({appId,nodeInfoList,instanceType:$('#instanceType').value,usePersonalQueue:$('#personalQueue').value})}); const data=await res.json().catch(()=>({})); if(!res.ok)throw new Error(data.error||`提交失败 (${res.status})`); state.task=data; renderTask(); toast('任务已提交','good'); if(data.taskId&&['RUNNING','QUEUED'].includes(data.status)){ clearInterval(state.poll); state.poll=setInterval(()=>queryTask(data.taskId),3000); }
  }catch(e){toast(e.message||'运行失败','bad')}finally{state.running=false;$('#runBtn').disabled=false;$('#runBtn').textContent='运行工作流 →'} }
$('#runBtn').onclick=runTask;
async function queryTask(taskId){ try{ const res=await fetch('/api/rh/query',{method:'POST',headers:{'Content-Type':'application/json','x-rh-key':apiKey()},body:JSON.stringify({taskId})}); const data=await res.json().catch(()=>({})); if(!res.ok)throw new Error(data.error||`查询失败 (${res.status})`); state.task=data; renderTask(); if(['SUCCESS','FAILED'].includes(data.status)){clearInterval(state.poll);state.poll=null;toast(data.status==='SUCCESS'?'任务完成':'任务失败',data.status==='SUCCESS'?'good':'bad')}}catch(e){clearInterval(state.poll);state.poll=null;toast(e.message,'bad')} }
function resultCard(x){ const t=(x.outputType||'').toLowerCase(),u=x.url||'',txt=x.text||''; let p=''; if(['png','jpg','jpeg','webp','gif','avif'].includes(t)&&u)p=`<img src="${esc(u)}" alt="output">`; else if(['mp4','webm','mov','m4v'].includes(t)&&u)p=`<video src="${esc(u)}" controls playsinline></video>`; else if(['mp3','wav','m4a','ogg','aac'].includes(t)&&u)p=`<audio src="${esc(u)}" controls></audio>`; else if(txt)p=`<pre>${esc(txt)}</pre>`; else p=`<b style="font-size:11px;color:#697580">${esc(t||'FILE')}</b>`; return `<div class="resultcard"><div class="preview">${p}</div><div class="meta">NODE ${esc(x.nodeId||'-')} · ${esc(t||'output')}${u?`<a href="${esc(u)}" target="_blank" rel="noreferrer">打开 ↗</a>`:''}</div></div>`; }
function renderTask(){ const t=state.task||{},st=t.status||'IDLE',usage=t.usage||{}; let h=`<div class="taskbar"><div><span>STATUS</span><b><i class="pilldot ${esc(st)}"></i>${esc(st)}</b></div><div><span>TASK ID</span><b>${esc(t.taskId||'-')}</b></div><div><span>COST</span><b>${esc(usage.consumeCoins??usage.consumeMoney??'-')}</b></div><div><span>TIME</span><b>${esc(usage.taskCostTime??'-')}</b></div></div>`; if(['RUNNING','QUEUED'].includes(st))h+=`<div class="empty">任务正在 ${esc(st)}，每 3 秒自动查询状态。</div>`; else if(st==='FAILED')h+=`<div class="empty" style="color:#ffaaaa">${esc(t.errorMessage||JSON.stringify(t.failedReason||{})||'任务失败')}</div>`; else if(Array.isArray(t.results)&&t.results.length)h+=`<div class="resultgrid">${t.results.map(resultCard).join('')}</div>`; else h+='<div class="empty">当前没有可展示的结果。</div>'; $('#resultArea').innerHTML=h; }
$('#toggleKey').onclick=()=>{ const i=$('#apiKeyInput'); i.type=i.type==='password'?'text':'password'; $('#toggleKey').textContent=i.type==='password'?'显示':'隐藏'; };
$('#saveKey').onclick=()=>{ const v=$('#apiKeyInput').value.trim(); if(!v)return toast('请输入 API Key','bad'); localStorage.setItem(LS.key,v); $('#apiKeyInput').value=''; updateKeyUI(); toast('API Key 已保存到当前浏览器','good'); };
$('#clearKey').onclick=()=>{ localStorage.removeItem(LS.key); $('#apiKeyInput').value=''; updateKeyUI(); toast('API Key 已清除'); };
$('#clearLocal').onclick=()=>{ [LS.app,LS.nodes,LS.inst,LS.queue].forEach(k=>localStorage.removeItem(k)); load(); toast('工作台本地数据已清除'); };
renderRoute(); load(); updateKeyUI(); if(!location.hash)route('workspace');